### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by CRY-D** [DJ-Raven/flatlaf-dashboard#1]
I tried to implement RTL (Right-to-Left) direction for this menu, but I failed. How can I achieve that?

**Comment by DJ-Raven** [comment]
Thank for reported 👍 
Updated by enable this [code](https://github.com/DJ-Raven/flatlaf-dashboard/blob/70d08d66fa48f72e55ae873cbc2968e4ac151b57/src/raven/application/Application.java#L87C13-L87C13) in class Application.java

**Comment by CRY-D** [comment]
The incorrect aspect of my actions was placing this particular code segment within the constructor rather than the main method. I genuinely appreciate your assistance and express my gratitude. Thank you.

![Screenshot from 2023-06-27 12-30-31](https://github.com/DJ-Raven/flatlaf-dashboard/assets/16564491/8afe99e1-8f7f-42f9-becb-c620671bbaea)
