### ISSUE TITLE
AccentColor on the darklight panel

### ISSUE THREAD

**Issue by CRY-D** [DJ-Raven/flatlaf-dashboard#2]
Hello Ravan, I tried implementing the custom Accentcolor feature, intending to place it below the 'dark & light' component, but it didn't appear. I know the issue is with the layout manager, and I ended up placing it at the top. Could you please help me put it in its appropriate place below the 'dark & light' component? 
Here's a picture showing what I want."
![DeepinScreenshot_tilix_20230704170533](https://github.com/DJ-Raven/flatlaf-dashboard/assets/16564491/e5052888-0afb-407b-be19-df0c3883f295)

**Comment by DJ-Raven** [comment]
Updated add accent color themes option on menu
You can check here for what I have add [code update](https://github.com/DJ-Raven/flatlaf-dashboard/commit/ad86cdaae7478937894c099d6a715cd589382301?diff=split#diff-229096be80838750c99570fa69746f13771b602911c46c6b68ff4cbdade630aaL15)

**Comment by CRY-D** [comment]
ur the best
