### ISSUE TITLE
Issue in resizing a window

### ISSUE THREAD

**Issue by CodingSkys** [DJ-Raven/flatlaf-dashboard#3]
HI, SIR, I AM HAVING A SMALL PROBLEM MY PAGES OF FRAMES OR FORMS REMAIN ON THE SAME SIZE AS THEY WERE BEFORE ON RESTORE DOWNSTATE WHEN I MAXIMIZE THE WINDOW ALL COMPONENTS REMAIN AS SAME SIZE THEY DO NOT GET ENLARGED WHEN I MAXIMIZE A WINDOW.
![issue github](https://github.com/DJ-Raven/flatlaf-dashboard/assets/140073645/09b6d2d5-3564-44bb-b9ce-bd72602825e0)
![issue github1](https://github.com/DJ-Raven/flatlaf-dashboard/assets/140073645/18b0d2ae-4d75-4a43-a791-0f0794a3b978)
In one picture you can see my window is not full and all the components are well managed but in the second picture you can see I maximize the window the components are stuck on top how can I make them responsive so that when I try to maximize the window all the components will spread on the full page?

**Comment by DJ-Raven** [comment]
When you design there component in netbeans and use free design layout or group layout you will have this option to resize component to horizontal and vertical

This free design layout we set to jpanel

![image](https://github.com/DJ-Raven/flatlaf-dashboard/assets/58245926/f5878522-2180-4209-ac12-5d2c6bc89ef3)

this we set the resize option to jtable

![2023-07-20_190439](https://github.com/DJ-Raven/flatlaf-dashboard/assets/58245926/ed00e117-dba7-4c07-9090-67e692a85989)
