### ISSUE TITLE
UI glitch 

### ISSUE THREAD

**Issue by anuragsgupta** [DJ-Raven/flatlaf-dashboard#4]
https://github.com/DJ-Raven/flatlaf-dashboard/assets/82273319/4e963210-1d15-4b69-b754-13aec0b5c4e6

https://github.com/DJ-Raven/flatlaf-dashboard/assets/82273319/cd6579c9-778c-4dd4-aa6d-499b4762f8b7

can you helf me how can i fix this issue

**Comment by DJ-Raven** [comment]
@anuragsgupta What jdk you are using. I thing you issue same as this : https://github.com/JFormDesigner/FlatLaf/issues/700
You can test it with jdk 8 or 11

**Comment by DJ-Raven** [comment]
You can try with latest version of 21
